/// <reference types='cypress'/>

describe('Narwal Sistema - Portal', function(){
    beforeEach(function(){
        cy.visit('https://cliente1regression.narwalsistemas.com.br/')
    })

    it.only('Teste de login (login correto)', function(){
        cy.get('#Login')
        .type('admin')
        cy.get('#senha')
        .type('S3gur@nc4-N@rv4lS1stem@s')
        cy.get('.send > input')
        .click()
        // cy.get('#BuscaMenu')
        // .type('usuario', {delay:0})
        // .type('{enter}')
        cy.contains('Administração')
        .click({force: true})
        cy.contains('Usuário')
        .click({force: true})
        cy.get('#btnNovo')
        .click()
        cy.get(':nth-child(3) > ul > .tbValue > #Nome')
        .type('testecy')
        cy.get(':nth-child(5) > ul > .tbValue > #Email')
        .type('cypress@narwalsistemas.com.br')
        cy.get(':nth-child(4) > ul > .tbValue > #Sobrenome')
        .type('testecy')
        cy.get(':nth-child(11) > .tbItem2 > ul > .tbValue > #Login')
        .type('testecy')
        // cy.get('.tbValue > .k-widget > .k-dropdown-wrap > .k-input')
        // .click(0)
        // cy.get('#btnAdicionar', {delay: 100})
        // .click()
        cy.get('.tbValue > .k-widget > .k-dropdown-wrap > .k-select')
        .click()
        cy.get('.k-item k-state-focused')
        .should('be.visible', 'Administradores')
        .select('Administradores')
    })

    it('Teste de login dando erro', function(){
        cy.get('#Login').type('saas', {delay:0})
        cy.get('#senha').type('S3gur@nc4-N@rv4lS1stem@s', {delay:0})
        cy.get('.send > input').click({delay:0})
        cy.get('li')
    })
})