/// <reference types="cypress"/>

describe('Portal Narwal', () => {
    beforeEach(() => {
        cy.visit('cliente1regression.narwalsistemas.com.br')
    })

    it('Teste: logar e criar usuário', () => {
        cy.loginNarwal()
        cy.get('[data-id="1"] > .k-header')
            .click({force: true})
        cy.get('[data-id="19"] > .k-link')
            .click({force: true})

        for(var i=1; i<=3; i++) {
            var a=i;
            cy.get('#btnNovo')
                .click({waitForAnimations: true})
            cy.get(':nth-child(3) > ul > .tbValue > #Nome')
                .type('TesteCy' + a, {delay: 0})
            cy.get(':nth-child(5) > ul > .tbValue > #Email')
                .type('TesteCy'+ a +'@narwalsistemas.com.br', {delay: 0})
            cy.get(':nth-child(4) > ul > .tbValue > #Sobrenome')
                .type('TesteCy' + a, {delay: 0})
            cy.get(':nth-child(11) > .tbItem2 > ul > .tbValue > #Login')
                .type('TesteCy' + a, {delay: 0})
            cy.get('.tbValue > .k-widget > .k-dropdown-wrap > .k-input')
                .type('{downArrow}')
                .type('{enter}')
            cy.get('.k-checkbox')
                .check({force: true})
            cy.get('#btnAdicionar')
                .click({waitForAnimations: true})
            cy.get('.noty_text')
                .should('have.text', 'Operação realizada com sucesso')
            cy.wait(1000) 
        }
    })

    it('Retornar erro ao tentar criar usuário', () => {
        cy.loginNarwal()
        cy.get('[data-id="1"] > .k-header')
            .click({force: true})
        cy.get('[data-id="19"] > .k-link')
            .click({force: true})
        cy.get('#btnNovo')
            .click({waitForAnimations: true})
        cy.get(':nth-child(3) > ul > .tbValue > #Nome')
            .type('TesteCy1', {delay: 0})
        cy.get(':nth-child(5) > ul > .tbValue > #Email')
            .type('TesteCy1@narwalsistemas.com.br', {delay: 0})
        cy.get(':nth-child(4) > ul > .tbValue > #Sobrenome')
            .type('TesteCy1', {delay: 0})
        cy.get(':nth-child(11) > .tbItem2 > ul > .tbValue > #Login')
            .type('TesteCy1', {delay: 0})
        cy.get('.tbValue > .k-widget > .k-dropdown-wrap > .k-input')
            .type('{downArrow}')
            .type('{enter}')
        cy.get('#btnAdicionar')
            .click()
        cy.get('.noty_text')
            .should('be.visible')
            .and('have.text', 'E-mail já utilizado em outro cadastro')
    })

    it.only('Cria Processo Expo', () => {
        cy.loginNarwal()
        cy.get('.buscar')
            .wait(1000)
            .type('Processo')
        cy.contains('Processo (expo)')
            .click({force: true})
        cy.get('#btnNovo')
            .click({waitForAnimations: true})
        cy.get(':nth-child(1) > ul > .tbValue > .k-widget > #InputExportacaoFilialId_Buscar')
            .type('a')
        cy.get('[data-offset-index="0"] > .dadosAuto > :nth-child(2)')
            .click({force: true})
        cy.get('.ExportadorDespachante > ul > .tbValue > .k-widget > #InputExportacaoImportadorId_Buscar')
            .type('a')
        cy.get('#InputExportacaoImportadorId_Buscar_listbox > [data-offset-index="0"] > .dadosAuto > .consultaCod')
            .click({force: true})
        cy.get(':nth-child(20) > ul > .tbValue > .k-widget > #InputExportacaoCompradorId_Buscar')
            .type('a')
        cy.get('#InputExportacaoCompradorId_Buscar_listbox > [data-offset-index="0"] > .dadosAuto > .consultaCod')
            .click({force: true})
        cy.get(':nth-child(31) > ul > .tbValue > .k-widget > .k-dropdown-wrap > .k-select')
            .type('{downArrow}')
            .type('{enter}')
        cy.get('[aria-controls="tabstripPrincipalExportacao-2"] > .k-link')
            .click({force: true})
        cy.get('#InputExportacaoIncotermId_Buscar')
            .type('a')
        cy.get('#InputExportacaoIncotermId_Buscar_listbox > [data-offset-index="0"] > .dadosAuto > .consultaCod')
            .click({force: true})
        cy.get('#InputExportacaoMoedaMercadoriaId_Buscar')
            .type('a')
        cy.get('#InputExportacaoMoedaMercadoriaId_Buscar_listbox > [data-offset-index="0"] > .dadosAuto > .consultaCod')
            .click({force: true})
        cy.get('[aria-controls="tabstripPrincipalExportacao-4"] > .k-link')
            .click({force: true})
        cy.get('#InputExportacaoViaTransporteId_Buscar')
            .type('a')
        cy.get('#InputExportacaoViaTransporteId_Buscar_listbox > [data-offset-index="0"] > .dadosAuto > .consultaCod')
            .click({force: true})
        cy.get('#InputExportacaoOrigemId_Buscar')
            .type('a')
        cy.get('#InputExportacaoOrigemId_Buscar_listbox > [data-offset-index="0"] > .dadosAuto > .consultaCod')
            .click({force: true})
        cy.get('#InputExportacaoDestinoId_Buscar')
            .type('a')
        cy.get('#InputExportacaoDestinoId_Buscar_listbox > [data-offset-index="0"] > .dadosAuto > .consultaCod')
            .click({force: true})
        cy.get('#btnAdicionar')
            .click({force: true})
    })
})